bitbag_sylius_cms_plugin_admin_api_frequently_asked_question:
    resource: |
        alias: bitbag_sylius_cms_plugin.frequently_asked_question
        identifier: code
        section: admin_api
        except: ['show']
        form: BitBag\SyliusCmsPlugin\Form\Type\FrequentlyAskedQuestionType
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api