bitbag_sylius_cms_plugin_admin_api_page:
    resource: |
        alias: bitbag_sylius_cms_plugin.page
        identifier: code
        section: admin_api
        except: ['show']
        form: BitBag\SyliusCmsPlugin\Form\Type\PageType
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api