imports:
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services/twig.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services/form.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services/factory.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services/event_listener.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services/controller.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services/fixture.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services/view_repository.yml" }

services:
    bitbag.resolver.block_resource:
        class: BitBag\CmsPlugin\Resolver\BlockResourceResolver
        arguments:
            - "@bitbag.repository.block"
            - "@logger"

    bitbag.resolver.block_template:
        class: BitBag\CmsPlugin\Resolver\BlockTemplateResolver