BitBag\CmsPlugin\Entity\Section:
    exclusion_policy: ALL
    xml_root_name: section
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Autocomplete, Default]
        code:
            expose: true
            type: string
            groups: [Autocomplete, Default]
    virtual_properties:
        getName:
            serialized_name: name
            groups: [Autocomplete, Default]
